# fly.toml app configuration file generated for shantanu-portfolio-v1-placeholder on 2026-09-28T13:50:02+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shantanu-portfolio-v1-placeholder'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
